version: "3"
services:
  worker:
    build: .
    restart: always
    image: registry.webix.io/reports-go
    volumes:
      - ./config.yml:/app/config.yml
      - ./meta.yml:/app/meta.yml
    ports:
      - 8014:8014
    links:
      - db:appdb
    command: /app/metadb --scheme /app/meta.yml


  db:
    restart: always
    image: mysql:8.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=1"
      - "MYSQL_DATABASE=reports"
