models:
  - id: companies
    name: Companies
    fields:
    - id: id
      name: ID
      key: true
      type: number
    - id: name
      name: Name
      filter: true
      type: text
      label: true
    - id: country
      name: Country
      filter: true
      type: text
    - id: city
      name: City
      filter: true
      type: text
    - id: address
      name: Address
      filter: true
      type: text
    - id: zip
      name: Zip
      filter: true
      type: text
    - id: phone
      name: Phone
      filter: true
      type: text
    - id: region_id
      name: Region
      filter: true
      type: picklist
      ref: regions

  - id: persons
    name: Persons
    fields:
    - id: id
      name: ID
      key: true
      type: number
    - id: last_name
      name: Last name
      filter: true
      type: text
    - id: first_name
      name: First name
      filter: true
      type: text
    - id: birthdate
      name: Birthdate
      filter: true
      type: date
    - id: country
      name: Country
      filter: true
      type: text
    - id: city
      name: City
      filter: true
      type: text
    - id: email
      name: Email
      filter: true
      type: text
      label: true
    - id: phone
      name: Phone
      filter: true
      type: text
    - id: job
      name: Job
      filter: true
      type: text
    - id: address
      name: Address
      filter: true
      type: text
    - id: company_id
      name: Company
      filter: true
      type: reference
      ref: companies
    - id: notify
      name: Notify
      filter: true
      type: boolean
    - id: age
      name: Age
      filter: true
      type: number

  - id: products
    name: Products
    fields:
    - id: id
      name: ID
      key: true
      type: number
    - id: maker
      name: Maker
      filter: true
      type: text
    - id: model
      name: Model
      filter: true
      type: text
      label: true
    - id: color
      name: Color
      filter: true
      type: text
    - id: year
      name: Year
      filter: true
      type: number
    - id: price
      name: Price
      filter: true
      type: number
    - id: owner
      name: Owner
      filter: true
      type: reference
      ref: persons
    - id: saler
      name: Saler
      filter: true
      type: reference
      ref: persons

  - id: sales
    name: Sales
    fields:
    - id: id
      name: ID
      key: true
      type: number
    - id: when
      name: When
      filter: true
      type: date
    - id: region_id
      name: Region
      filter: true
      type: picklist
      ref: regions
    - id: discount
      name: Discount
      filter: true
      type: number
    - id: price
      name: Price
      filter: true
      type: number
      label: true
    - id: customer_id
      name: Customer
      filter: true
      type: reference
      ref: persons
    - id: product_id
      name: Product
      filter: true
      type: reference
      ref: products

picklists:
  - id: regions
    options:
      - id: 1
        value: South
      - id: 2
        value: North
      - id: 3
        value: East
      - id: 4
        value: West
